class EnvironmentSettings:
    def __init__(self):
        self.unimod1k_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/dataset/TrainSet'
        self.unimod1k_dir_nlp = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/dataset/TrainSet'
        self.workspace_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/tensorboard'    # Directory for tensorboard files.
        self.pretrained_models = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/pretrained_models'
        self.lasot_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/lasot'
        self.got10k_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/got10k'
        self.lasot_lmdb_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/got10k_lmdb'
        self.trackingnet_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/trackingnet'
        self.trackingnet_lmdb_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/trackingnet_lmdb'
        self.coco_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/coco'
        self.coco_lmdb_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/vid'
        self.imagenet_lmdb_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.rgbd_dir = '/public/home/lxy/bao_3/UniMod1K/SPT_bk2/dataset/TrainSet'
